apiVersion: v1
kind: Secret
metadata:
  name: node-app-secret
  namespace: argocd  # Replace with your actual namespace if different
type: Opaque
data:
  username: YWRtaW4=    # Base64 encoded 'admin'
  password: c2VjcmV0MTIz  # Base64 encoded 'secret123'
